"""Claude token usage log: how many tokens went into building Vicky Racer.

Reads every Claude Code session transcript for this project (~/.claude/projects/<project>/*.jsonl),
counts each API response once (transcripts repeat a response for every content block it streams),
and writes docs/TOKEN_USAGE.md with totals, a per-session table and a per-day table. Re-run it any
time to refresh the log; it always rebuilds from the transcripts, so it never double-counts.

    python tools/dev/token_usage.py [--out docs/TOKEN_USAGE.md] [--transcripts <dir>]
"""
import argparse
import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIELDS = ["input_tokens", "cache_creation_input_tokens", "cache_read_input_tokens", "output_tokens"]
HEADERS = ["Input", "Cache write", "Cache read", "Output", "Total"]


def default_transcripts() -> Path:
    # Claude Code names the folder after the project path with ':' '\' '/' turned into '-'.
    slug = "".join("-" if c in ":\\/" else c for c in str(ROOT))
    return Path.home() / ".claude" / "projects" / slug


def read_session(path: Path) -> tuple[dict, list[str]]:
    """Return {response id: (timestamp, model, usage)} and the session's timestamps."""
    responses, stamps = {}, []
    with path.open(encoding="utf-8") as f:
        for line in f:
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if entry.get("timestamp"):
                stamps.append(entry["timestamp"])
            msg = entry.get("message")
            if not isinstance(msg, dict) or "usage" not in msg or msg.get("model") == "<synthetic>":
                continue
            key = entry.get("requestId") or msg.get("id")
            responses[key] = (entry.get("timestamp", ""), msg.get("model", "?"), msg["usage"])
    return responses, stamps


def title_of(path: Path) -> str:
    meta = path.with_suffix("") / "custom-title.json"
    try:
        return json.loads(meta.read_text(encoding="utf-8"))["customTitle"]
    except (OSError, KeyError, json.JSONDecodeError):
        return path.stem[:8]


def add(total: dict, usage: dict) -> None:
    for field in FIELDS:
        total[field] += usage.get(field) or 0


def row(label: str, t: dict, extra: list[str] = ()) -> str:
    cells = [t[f] for f in FIELDS] + [sum(t[f] for f in FIELDS)]
    return "| " + " | ".join([label, *extra, *(f"{c:,}" for c in cells)]) + " |"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--transcripts", type=Path, default=default_transcripts())
    parser.add_argument("--out", type=Path, default=ROOT / "docs" / "TOKEN_USAGE.md")
    args = parser.parse_args()

    sessions, per_day, per_model = [], defaultdict(lambda: defaultdict(int)), defaultdict(lambda: defaultdict(int))
    grand, calls = defaultdict(int), 0
    for path in args.transcripts.glob("*.jsonl"):
        responses, stamps = read_session(path)
        if not responses:
            continue
        total = defaultdict(int)
        for stamp, model, usage in responses.values():
            add(total, usage)
            add(grand, usage)
            add(per_model[model], usage)
            add(per_day[stamp[:10]], usage)
        calls += len(responses)
        sessions.append((min(stamps), max(stamps), title_of(path), len(responses), total))
    sessions.sort()

    def day(stamp: str) -> str:
        return datetime.fromisoformat(stamp.replace("Z", "+00:00")).astimezone().strftime("%Y-%m-%d %H:%M")

    lines = [
        "# Claude token usage",
        "",
        "Tokens Claude (Claude Code) spent building Vicky Racer, counted from the session transcripts.",
        f"Generated by `python tools/dev/token_usage.py` on {datetime.now():%Y-%m-%d %H:%M}; re-run it to refresh.",
        "",
        "- **Input**: fresh prompt tokens. **Cache write / read**: prompt tokens written to / served from the",
        "  prompt cache (reads are billed at a fraction of input). **Output**: tokens Claude wrote, including thinking.",
        "- Counts the main conversation of each session; ComfyUI/Blender asset renders run locally and use no tokens.",
        "",
        "## Totals",
        "",
        f"- Sessions: **{len(sessions)}**, API responses: **{calls:,}**",
        f"- Output tokens: **{grand['output_tokens']:,}**",
        f"- Prompt tokens (input + cache write + cache read): **{sum(grand[f] for f in FIELDS[:3]):,}**",
        f"- All tokens: **{sum(grand[f] for f in FIELDS):,}**",
        "",
        "## By session",
        "",
        "| Session | Started | Last activity | Responses | " + " | ".join(HEADERS) + " |",
        "|---|---|---|---:|" + "---:|" * len(HEADERS),
    ]
    for start, end, title, n, total in sessions:
        lines.append(row(title, total, [day(start), day(end), f"{n:,}"]))
    lines.append(row("**Total**", grand, ["", "", f"{calls:,}"]))
    lines += ["", "## By day (UTC)", "", "| Day | " + " | ".join(HEADERS) + " |", "|---|" + "---:|" * len(HEADERS)]
    lines += [row(d, per_day[d]) for d in sorted(per_day)]
    lines += ["", "## By model", "", "| Model | " + " | ".join(HEADERS) + " |", "|---|" + "---:|" * len(HEADERS)]
    lines += [row(f"`{m}`", per_model[m]) for m in sorted(per_model)]

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({len(sessions)} sessions, {calls:,} responses)")


if __name__ == "__main__":
    main()
