class_name CarWheels
extends RefCounted
## Where the tyres are in every car body, for the rolling tread (actors/car/rolling_tread.gd).
## GENERATED by tools/comfy/wheel_rects.py from the PNGs in art/cars: re-run it after building
## new cars or paints instead of editing this file.
##
## Per body (path under art/cars): rear left, front left, rear right, front right, in texture
## pixels. Left is the top of the image, the car's left as it faces +X. A body that is not
## listed (the Bubble Car, whose tyres hardly show) just has no rolling tread.

const BODIES := {
	"car_blue.png": [Rect2i(25, 3, 27, 9), Rect2i(78, 3, 24, 9), Rect2i(25, 60, 27, 9), Rect2i(78, 61, 24, 8)],
	"car_green.png": [Rect2i(26, 3, 25, 10), Rect2i(77, 3, 25, 9), Rect2i(26, 60, 25, 9), Rect2i(77, 61, 25, 8)],
	"car_red.png": [Rect2i(29, 3, 21, 9), Rect2i(78, 3, 26, 9), Rect2i(29, 60, 21, 9), Rect2i(78, 61, 26, 8)],
	"car_yellow.png": [Rect2i(25, 3, 26, 9), Rect2i(77, 3, 24, 9), Rect2i(25, 60, 26, 9), Rect2i(77, 61, 24, 8)],
	"paint/banana_blue.png": [Rect2i(26, 3, 26, 9), Rect2i(74, 3, 24, 8), Rect2i(26, 61, 26, 8), Rect2i(74, 61, 24, 8)],
	"paint/banana_green.png": [Rect2i(26, 3, 26, 9), Rect2i(75, 3, 24, 9), Rect2i(26, 60, 26, 9), Rect2i(75, 61, 24, 8)],
	"paint/banana_pink.png": [Rect2i(26, 3, 26, 9), Rect2i(74, 3, 25, 9), Rect2i(26, 61, 26, 8), Rect2i(74, 61, 25, 8)],
	"paint/banana_purple.png": [Rect2i(26, 3, 25, 9), Rect2i(75, 3, 25, 9), Rect2i(26, 61, 25, 8), Rect2i(75, 61, 25, 8)],
	"paint/banana_yellow.png": [Rect2i(26, 3, 26, 9), Rect2i(75, 3, 24, 9), Rect2i(26, 60, 26, 8), Rect2i(75, 61, 24, 8)],
	"paint/dragon_blue.png": [Rect2i(30, 7, 21, 7), Rect2i(77, 7, 20, 7), Rect2i(30, 58, 21, 7), Rect2i(77, 58, 20, 7)],
	"paint/dragon_green.png": [Rect2i(29, 6, 23, 8), Rect2i(75, 6, 22, 8), Rect2i(29, 58, 23, 8), Rect2i(75, 59, 22, 7)],
	"paint/dragon_pink.png": [Rect2i(29, 6, 22, 8), Rect2i(76, 7, 21, 7), Rect2i(29, 58, 22, 7), Rect2i(76, 59, 21, 6)],
	"paint/dragon_purple.png": [Rect2i(29, 7, 22, 7), Rect2i(76, 7, 21, 7), Rect2i(29, 58, 22, 7), Rect2i(76, 59, 21, 6)],
	"paint/dragon_yellow.png": [Rect2i(30, 7, 21, 7), Rect2i(77, 7, 20, 7), Rect2i(30, 58, 21, 7), Rect2i(77, 58, 20, 7)],
	"paint/formula_blue.png": [Rect2i(32, 4, 20, 16), Rect2i(75, 2, 20, 18), Rect2i(32, 52, 20, 16), Rect2i(75, 52, 20, 17)],
	"paint/formula_green.png": [Rect2i(32, 4, 19, 16), Rect2i(75, 2, 21, 18), Rect2i(32, 52, 19, 15), Rect2i(75, 52, 21, 17)],
	"paint/formula_pink.png": [Rect2i(31, 4, 20, 16), Rect2i(75, 2, 21, 18), Rect2i(31, 52, 20, 16), Rect2i(75, 52, 21, 17)],
	"paint/formula_purple.png": [Rect2i(31, 4, 20, 16), Rect2i(74, 3, 21, 17), Rect2i(31, 52, 20, 16), Rect2i(74, 52, 21, 18)],
	"paint/formula_yellow.png": [Rect2i(31, 4, 20, 16), Rect2i(75, 2, 19, 18), Rect2i(31, 52, 20, 16), Rect2i(75, 52, 19, 17)],
	"paint/grippy_blue.png": [Rect2i(31, 3, 26, 13), Rect2i(71, 3, 26, 13), Rect2i(31, 56, 26, 13), Rect2i(71, 57, 26, 12)],
	"paint/grippy_green.png": [Rect2i(31, 3, 26, 14), Rect2i(71, 3, 26, 13), Rect2i(31, 56, 26, 13), Rect2i(71, 56, 26, 13)],
	"paint/grippy_pink.png": [Rect2i(31, 3, 26, 13), Rect2i(72, 3, 26, 13), Rect2i(31, 56, 26, 13), Rect2i(72, 56, 26, 13)],
	"paint/grippy_purple.png": [Rect2i(31, 3, 26, 13), Rect2i(72, 2, 26, 14), Rect2i(31, 56, 26, 13), Rect2i(72, 57, 26, 12)],
	"paint/grippy_yellow.png": [Rect2i(31, 3, 26, 13), Rect2i(71, 3, 26, 13), Rect2i(31, 56, 26, 13), Rect2i(71, 56, 26, 13)],
	"paint/icecream_blue.png": [Rect2i(25, 3, 27, 9), Rect2i(77, 3, 25, 9), Rect2i(25, 60, 27, 9), Rect2i(77, 61, 25, 8)],
	"paint/icecream_green.png": [Rect2i(25, 3, 26, 9), Rect2i(77, 3, 24, 9), Rect2i(25, 60, 26, 9), Rect2i(77, 60, 24, 9)],
	"paint/icecream_pink.png": [Rect2i(26, 3, 25, 9), Rect2i(77, 3, 24, 9), Rect2i(26, 60, 25, 9), Rect2i(77, 61, 24, 8)],
	"paint/icecream_purple.png": [Rect2i(26, 3, 25, 9), Rect2i(77, 3, 25, 9), Rect2i(26, 61, 25, 8), Rect2i(77, 61, 25, 8)],
	"paint/icecream_yellow.png": [Rect2i(25, 3, 25, 9), Rect2i(77, 3, 24, 9), Rect2i(25, 60, 25, 8), Rect2i(77, 61, 24, 8)],
	"paint/kart_blue.png": [Rect2i(31, 3, 24, 9), Rect2i(79, 4, 22, 16), Rect2i(31, 60, 24, 9), Rect2i(79, 52, 22, 16)],
	"paint/kart_green.png": [Rect2i(31, 3, 25, 9), Rect2i(80, 4, 23, 16), Rect2i(31, 61, 25, 8), Rect2i(80, 52, 23, 16)],
	"paint/kart_pink.png": [Rect2i(31, 3, 25, 9), Rect2i(80, 4, 22, 16), Rect2i(31, 61, 25, 8), Rect2i(80, 54, 22, 14)],
	"paint/kart_purple.png": [Rect2i(32, 3, 24, 9), Rect2i(80, 4, 22, 16), Rect2i(32, 61, 24, 8), Rect2i(80, 53, 22, 15)],
	"paint/kart_yellow.png": [Rect2i(32, 3, 24, 9), Rect2i(80, 4, 22, 16), Rect2i(32, 60, 24, 9), Rect2i(80, 52, 22, 16)],
	"paint/monster_blue.png": [Rect2i(34, 3, 26, 13), Rect2i(70, 3, 26, 13), Rect2i(34, 57, 26, 12), Rect2i(70, 57, 26, 12)],
	"paint/monster_green.png": [Rect2i(34, 3, 25, 13), Rect2i(70, 3, 26, 13), Rect2i(34, 57, 25, 12), Rect2i(70, 57, 26, 12)],
	"paint/monster_pink.png": [Rect2i(34, 2, 26, 14), Rect2i(70, 2, 26, 14), Rect2i(34, 57, 26, 12), Rect2i(70, 57, 26, 12)],
	"paint/monster_purple.png": [Rect2i(34, 3, 25, 13), Rect2i(70, 3, 26, 13), Rect2i(34, 57, 25, 12), Rect2i(70, 57, 26, 12)],
	"paint/monster_yellow.png": [Rect2i(35, 3, 25, 12), Rect2i(70, 3, 26, 12), Rect2i(35, 57, 25, 12), Rect2i(70, 57, 26, 12)],
	"paint/police_blue.png": [Rect2i(25, 3, 27, 9), Rect2i(77, 3, 24, 8), Rect2i(25, 61, 27, 8), Rect2i(77, 62, 24, 7)],
	"paint/police_green.png": [Rect2i(31, 3, 21, 9), Rect2i(81, 3, 19, 8), Rect2i(31, 61, 21, 8), Rect2i(81, 61, 19, 8)],
	"paint/police_pink.png": [Rect2i(24, 3, 27, 8), Rect2i(75, 3, 25, 8), Rect2i(24, 61, 27, 8), Rect2i(75, 61, 25, 8)],
	"paint/police_purple.png": [Rect2i(25, 3, 27, 9), Rect2i(76, 3, 24, 8), Rect2i(25, 61, 27, 8), Rect2i(76, 62, 24, 7)],
	"paint/police_yellow.png": [Rect2i(25, 3, 27, 8), Rect2i(76, 3, 24, 8), Rect2i(25, 61, 27, 8), Rect2i(76, 61, 24, 8)],
	"paint/rocket_blue.png": [Rect2i(46, 4, 24, 8), Rect2i(91, 3, 23, 9), Rect2i(46, 60, 24, 8), Rect2i(91, 61, 23, 8)],
	"paint/rocket_green.png": [Rect2i(46, 4, 23, 8), Rect2i(90, 3, 24, 9), Rect2i(46, 60, 23, 8), Rect2i(90, 61, 24, 8)],
	"paint/rocket_pink.png": [Rect2i(45, 4, 23, 8), Rect2i(91, 3, 23, 9), Rect2i(45, 60, 23, 8), Rect2i(91, 61, 23, 8)],
	"paint/rocket_purple.png": [Rect2i(45, 4, 24, 8), Rect2i(90, 3, 24, 9), Rect2i(45, 60, 24, 8), Rect2i(90, 61, 24, 8)],
	"paint/rocket_yellow.png": [Rect2i(45, 3, 24, 9), Rect2i(91, 3, 24, 9), Rect2i(45, 60, 24, 8), Rect2i(91, 61, 24, 8)],
	"paint/slider_blue.png": [Rect2i(25, 3, 26, 9), Rect2i(75, 3, 25, 9), Rect2i(25, 60, 26, 8), Rect2i(75, 61, 25, 8)],
	"paint/slider_green.png": [Rect2i(26, 3, 26, 9), Rect2i(75, 3, 24, 9), Rect2i(26, 60, 26, 9), Rect2i(75, 61, 24, 8)],
	"paint/slider_pink.png": [Rect2i(25, 3, 27, 9), Rect2i(75, 3, 26, 9), Rect2i(25, 60, 27, 8), Rect2i(75, 61, 26, 8)],
	"paint/slider_purple.png": [Rect2i(25, 3, 26, 9), Rect2i(75, 3, 25, 9), Rect2i(25, 61, 26, 8), Rect2i(75, 61, 25, 8)],
	"paint/slider_yellow.png": [Rect2i(25, 3, 27, 9), Rect2i(75, 3, 26, 9), Rect2i(25, 60, 27, 9), Rect2i(75, 61, 26, 8)],
	"paint/starter_blue.png": [Rect2i(25, 3, 27, 9), Rect2i(78, 3, 24, 9), Rect2i(25, 60, 27, 9), Rect2i(78, 61, 24, 8)],
	"paint/starter_green.png": [Rect2i(26, 3, 25, 10), Rect2i(77, 3, 25, 9), Rect2i(26, 60, 25, 9), Rect2i(77, 61, 25, 8)],
	"paint/starter_pink.png": [Rect2i(25, 3, 26, 9), Rect2i(76, 3, 26, 9), Rect2i(25, 61, 26, 8), Rect2i(76, 61, 26, 8)],
	"paint/starter_purple.png": [Rect2i(26, 3, 26, 9), Rect2i(77, 3, 25, 9), Rect2i(26, 61, 26, 8), Rect2i(77, 61, 25, 8)],
	"paint/starter_yellow.png": [Rect2i(25, 3, 26, 9), Rect2i(77, 3, 24, 9), Rect2i(25, 60, 26, 9), Rect2i(77, 61, 24, 8)],
	"setups/banana.png": [Rect2i(25, 3, 26, 9), Rect2i(76, 3, 26, 9), Rect2i(25, 60, 26, 9), Rect2i(76, 61, 26, 8)],
	"setups/dragon.png": [Rect2i(28, 6, 23, 8), Rect2i(76, 6, 23, 8), Rect2i(28, 58, 23, 8), Rect2i(76, 59, 23, 7)],
	"setups/formula.png": [Rect2i(31, 4, 20, 16), Rect2i(76, 2, 21, 14), Rect2i(31, 52, 20, 16), Rect2i(76, 52, 21, 17)],
	"setups/grippy.png": [Rect2i(30, 3, 27, 13), Rect2i(73, 3, 26, 13), Rect2i(30, 56, 27, 13), Rect2i(73, 56, 26, 13)],
	"setups/icecream.png": [Rect2i(24, 3, 26, 9), Rect2i(78, 3, 24, 9), Rect2i(24, 60, 26, 9), Rect2i(78, 61, 24, 8)],
	"setups/kart.png": [Rect2i(32, 3, 23, 9), Rect2i(81, 4, 23, 16), Rect2i(32, 60, 23, 9), Rect2i(81, 53, 23, 15)],
	"setups/monster.png": [Rect2i(35, 3, 25, 13), Rect2i(72, 3, 25, 13), Rect2i(35, 57, 25, 12), Rect2i(72, 57, 25, 12)],
	"setups/police.png": [Rect2i(23, 3, 29, 9), Rect2i(77, 3, 26, 8), Rect2i(23, 60, 29, 9), Rect2i(77, 61, 26, 8)],
	"setups/rocket.png": [Rect2i(51, 4, 18, 8), Rect2i(93, 3, 23, 9), Rect2i(51, 60, 18, 8), Rect2i(93, 61, 23, 8)],
	"setups/slider.png": [Rect2i(25, 3, 27, 9), Rect2i(76, 3, 26, 8), Rect2i(25, 60, 27, 9), Rect2i(76, 61, 26, 8)],
	"setups/starter.png": [Rect2i(29, 3, 21, 9), Rect2i(78, 3, 26, 9), Rect2i(29, 60, 21, 9), Rect2i(78, 61, 26, 8)],
}


## The four tyre rectangles of `texture`, or an empty array.
static func of(texture: Texture2D) -> Array:
	if texture == null:
		return []
	return BODIES.get(texture.resource_path.trim_prefix("res://art/cars/"), [])
